### ISSUE TITLE
Create release for first call for comments

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/eas-schemas#102]
...and add the Schematron file to the same ZIP file?

**Comment by kerstarno** [comment]
@fordmadox - if the Schematron can be added to the release in this branch here that would be ideal.

**Comment by fordmadox** [comment]
@kerstarno :  let me know if you'd like to adjust (especially as we iron out any other remaining issues), but check out https://github.com/SAA-SDT/eas-schemas/releases/tag/v0.1.0-alpha.

**Comment by kerstarno** [comment]
Hi @fordmadox - the release in itself looks good to me. 

Only question that I'd have: did we, when releasing the draft of EAC-CPF, also include the source files for the schema? I'm mainly asking as I'm wondering whether it might be confusing for members of the community at the stage of asking feedback on EAD, that this also includes the EAC-CPF schemas. So, my question is mainly: would it be possible to exclude the "eac-cpf" subfolder from the "xml-schemas" folder?

If this isn't possible or too much of a fuzz, we can leave it as it is and should then mainly make sure to explain this in the release note.

**Comment by fordmadox** [comment]
Oddly, I cannot figure out a way to remove the parent folders just yet (outside of the 'vendor' one), but I have created a new release that removes the EAC files from the release.  See https://github.com/SAA-SDT/eas-schemas/releases/tag/v0.1.0-alpha

**Comment by kerstarno** [comment]
With the call for comments published, I am closing this issue.
