### ISSUE TITLE
EAD4: allow single <fromDate> in <dateRange>

### ISSUE THREAD

**Issue by vns2** [SAA-SDT/eas-schemas#127]
## Creator of issue

Nils Meyer
Landesarchiv Baden-Württemberg
[nils.meyer@la-bw.de](mailto:nils.meyer@la-bw.de)

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: The `<xs:choice>` group in `<dateRange>` should not only allow the `<fromDate>` + `<toDate>` sequence and the single `<toDate>` element. It should also allow a single `<fromDate>` element. This would be helpful when describing for example a collection of documents that is not concluded yet. It could also be necessary for example in `<useConditions>` and `<accessConditions>` to define a date from which a certain license or access condition will apply in the future. Due to archival and copyright laws, it is common that licenses and access conditions change over time. It would be helpful to be able to record this information in EAD.

## Suggested Solution

* Text: Make it possible to use a single `<fromDate>` element in the `<xs:choice>` group in `<dateRange>`.

## Context

* Text: In the German Digital Library and the German Archives Portal, it is becoming more and more necessary to correctly depict use and access conditions with the correct dates they apply. Especially for future concepts of a digital reading room it is necessary to provide a date from which certain use and/or access conditions apply.

**Comment by kerstarno** [comment]
This is possible already. The current definition of `<dateRange>` has `<toDate>` as optional, i.e. it is possible to use `<dateRange>` only with a `<fromDate>` sub-element.

```
<xs:complexType name="dateRange">
  <xs:choice>
    <xs:sequence>
      <xs:element type="ead:fromDate" name="fromDate"/>
      <xs:element type="ead:toDate" name="toDate" minOccurs="0"/>
    </xs:sequence>
    <xs:element type="ead:toDate" name="toDate"/>
  </xs:choice>
 [...]
</xs:complexType>
```

On the first level (within `<xs:choice>`), the options are between either using both sub-elements or only `<toDate>`. On the second level (within `<xs:sequence>`), the options are to either use `<fromDate>` followed by `<toDate>` or to only use `<fromDate>`, as only this is required.
