### ISSUE TITLE
Links to vocabularies in <controlAccess> sub-elements (and others)

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#13]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
* Text: A new set of attributes dedicated to referencing vocabularies and specific entries from vocabularies should be added. These would focus on encoding URI-s, for the vocabulary source in general and for the specific entry, as well as allowing for a vocabulary source to be provided as a literal. These attributes would be made available with all elements that might contain terms from vocabularies, ontologies, thesauri, etc. - either themselves or their sub-elements.

## Suggested Solution
* Text: Rename attribute `@identifier` to `@valueURI`. Rename attribute `@source` to `@vocabularySource`. Add new  attribute `@vocabularySourceURI`. Enable these attributes with appropriate elements.

**Comment by kerstarno** [comment]
This issue looks at the use of vocabulary attributes that mainly appear within the sub-elements of `<controlAccess>`, but are also used in some other elements of EAD. Out of the ten sub-elements of `<controlAccess>`, `<geogname>` is excluded as it will be dealt with differently in the context of aligning the encoding of places and place names between EAD and EAC-CPF (see #42). 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

- [ ] **Replace `@identifier` with `@valueURI`; change data type from token to anyURI** _(note: while anyURI is stricter than token, it still is rather generic; as long as values don't make inappropriate use of reserved characters, such as containing  multiple # characters or having % characters that are not followed by two hexadecimal digits, values of `@identifier` should remain technically valid also in `@valueURI` when transformed from EAD3 to EAD 4.0)_
  - [ ] In `<corpName>`
  - [ ] In `<famName>`
  - [ ] In `<persName>`
  - [ ] In `<name>`
  - [ ] In `<function>`
  - [ ] In `<occupation>`
  - [ ] In `<subject>`
  - [ ] In `<genreForm>`
  - [ ] In `<title>`
  - [ ] In `<dao>`
  - [ ] In `<unitId>` 
  - [ ] In `<unitType>`
  - [ ] In `<physFacet>`
- [ ] **Replace `@source` with `@vocabularySource`**
  - [ ] In `<corpName>`
  - [ ] In `<famName>`
  - [ ] In `<persName>`
  - [ ] In `<name>`
  - [ ] In `<function>`
  - [ ] In `<occupation>`
  - [ ] In `<subject>`
  - [ ] In `<genreForm>`
  - [ ] In `<title>`
  - [ ] In `<unitType>`
  - [ ] In `<physFacet>`
- [ ] **Add `@vocabularySourceURI` (data type: anyURI) to**
  - [ ] `<corpName>`
  - [ ] `<famName>`
  - [ ] `<persName>`
  - [ ] `<name>`
  - [ ] `<function>`
  - [ ] `<occupation>`
  - [ ] `<subject>`
  - [ ] `<genreForm>`
  - [ ] `<title>`
  - [ ] `<unitType>`
  - [ ] `<physFacet>`
- [ ] **Remove `@rules` from** _(note: all of these will include `@conventionDeclarationReference` in EAD 4.0, which can be used to point to rules referenced and/or described in `<conventionDeclaration>`, see #11)_
  - [ ] `<corpName>`
  - [ ] `<famName>`
  - [ ] `<persName>`
  - [ ] `<name>`
  - [ ] `<function>`
  - [ ] `<occupation>`
  - [ ] `<subject>`
  - [ ] `<genreForm>`
  - [ ] `<title>`
  - [ ] `<unitType>`
  - [ ] `<physFacet>`
- [ ] **Remove `@normal` from**
  - [ ] `<corpName>`
  - [ ] `<famName>`
  - [ ] `<persName>`
  - [ ] `<name>`
  - [ ] `<function>`
  - [ ] `<occupation>`
  - [ ] `<subject>`
  - [ ] `<genreForm>`
  - [ ] `<title>`
- [ ] **Remove `@relator` from**
  - [ ] `<corpName>`
  - [ ] `<famName>`
  - [ ] `<persName>`
  - [ ] `<name>`
  - [ ] `<function>`
  - [ ] `<occupation>`
  - [ ] `<subject>`
  - [ ] `<genreForm>`
  - [ ] `<title>`
- [ ] **Add `<targetRole>` as an optional and repeatable sub-element to**
  - [ ] `<corpName>`
  - [ ] `<famName>`
  - [ ] `<persName>`
  - [ ] `<name>`
  - [ ] `<function>`
  - [ ] `<occupation>`
  - [ ] `<subject>`
  - [ ] `<genreForm>`
  - [ ] `<title>`

Additionally, for alignment with EAC-CPF with regard to shared elements:
- [ ] Remove `@identifier`, `@source`, `@rules` from `<term>` without replacement (currently only in EAC-CPF, though, after the removal of `<localControl>`)
- [ ] Remove `@identifier`, `@source`, `@rules` from `<part>` without replacement

**Comment by fordmadox** [comment]
Ready for testing.

**Comment by kerstarno** [comment]
> **Update (4 January 2024) to the original details from July 2023 (see comment before the previous one)**

Building on the change suggested with #67, the remaining changes to take care of in this issue here are:

- [x] **Replace `@identifier` with `@valueURI`; change data type from token to anyURI** _(note: while anyURI is stricter than token, it still is rather generic; as long as values don't make inappropriate use of reserved characters, such as containing  multiple # characters or having % characters that are not followed by two hexadecimal digits, values of `@identifier` should remain technically valid also in `@valueURI` when transformed from EAD3 to EAD 4.0)_
  - [ ] In `<function>`
  - [ ] In `<subject>`
  - [ ] In `<unitId>` 
  - [ ] In `<unitType>`
  - [ ] In `<physFacet>`
- [x] **Replace `@source` with `@vocabularySource`**
  - [ ] In `<function>`
  - [ ] In `<subject>`
  - [ ] In `<unitType>`
  - [ ] In `<physFacet>`
- [x] **Add `@vocabularySourceURI` (data type: anyURI) to**
  - [ ] `<function>`
  - [ ] `<subject>`
  - [ ] `<unitType>`
  - [ ] `<physFacet>`
- [x] **Remove `@rules` from** _(note: all of these will include `@conventionDeclarationReference` in EAD 4.0, which can be used to point to rules referenced and/or described in `<conventionDeclaration>`, see #11)_
  - [ ] `<function>`
  - [ ] `<subject>`
  - [ ] `<unitType>`
  - [ ] `<physFacet>`
- [x] **Remove `@normal` from**
  - [ ] `<function>`
  - [ ] `<subject>`
- [x] **Remove `@relator` from**
  - [ ] `<function>`
  - [ ] `<subject>`
- [x] **Add `<targetRole>` as an optional and repeatable sub-element to**
  - [ ] `<function>`
  - [ ] `<subject>`

Additionally, for alignment with EAC-CPF with regard to shared elements:
- [ ] Remove `@identifier`, `@source`, `@rules` from `<term>` without replacement (currently only in EAC-CPF, though, after the removal of `<localControl>`)
- [ ] Remove `@identifier`, `@source`, `@rules` from `<part>` without replacement

New, as missed in the original comment:
- [ ] Add `@vocabularySource` (data type: token) and `@vocabularySourceURI` (data type: anyURI) to `<unitId>` to ensure that the three vocabulary attributes are always used together

_Explanation regarding the changes compared to the original comment: `<corpname>`, `<famname>`, `<name>` and `<persname>` as sub-elements of `<controlaccess>` will all become `<agent>` (#58); `<occupation>` and `<genreform>` as sub-elements of `<controlaccess>` will be incorporated as subject headings (#67); `<title>` as sub-element of `<controlaccess>` will be suggested to be moved to `<bibliography>`, now  renamed `<publicationNote>`; all of these elements when used in mixed content contexts will be incorporated as `<referringString>` (#63)_

**Comment by karinbredenberg** [comment]
All that are ready have been tested.

**Comment by kerstarno** [comment]
Retested with XSD and RNG and can confirm that all the above changes are now in place. 

There were some changes required to how `<title>` was defined in addition to the aspects mentioned  above. I created a pull request (#75) for those. As these changes, however, do not affect this issue here, I will mark it as tested successfully.
