### ISSUE TITLE
Suggestion of a new value "download" for attribute @show

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/eas-schemas#22]
## Creator of issue
1. Nils Meyer, Baden-Württemberg State Archives, Germany, [nils.meyer@la-bw.de](mailto:nils.meyer@la-bw.de)

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [X] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
* Text: Hello, I would like to suggest a new value for the attribute @show in EAD3. 
At the moment there is no designated value for links that trigger a download. 
A "download" value would enable for example websites and online portals that 
use EAD-data to distinguish download links from other link types. This would 
be very helpful, especially for usability and accessibility reasons.
Thank you very much!

## Suggested Solution

* Text: create a new value for @show: "download"

## Context

* Text: This issue originated from the German national EAD working group. 
Our group consists of representatives from German state archives and 
municipal archives as well as archival web applications and national web 
portals, such as Arcinsys, the German Archives Portal, The German Digital 
Library (partner of Europeana). At the moment we are preparing a shift from 
the current German EAD 2002 profile to EAD3. Since usability and accessibility 
are becoming more and more important in our community, a solution to 
designate download links in our data would be very helpful. With this,  
download links could also be designated as such on websites and in online 
portals.

**Comment by kerstarno** [comment]
Apologies for not getting back to this issue earlier. The suggestion was discussed at the EAD team meeting on 21 October 2022 and it was decided not to add the suggested value to the attribute `@show`. The reasons for this decision are as follows:

- As the attribute originates from XLink, adding a new value that is not available in the original context is seen as an overload to the initial conceptualisation (see e.g. https://www.w3.org/TR/xlink11/#show-att and https://www.w3.org/TR/xlink11/#link-semantics for background).
- No browser would automatically know what to do with this value, i.e. even if the value were added, implementers would always need to take care of any function resulting from this value in other ways.
- Prospectively, the attribute `@show` won't remain in the next version of EAD.
