### ISSUE TITLE
Change occurrence of @maintenanceStatus, @maintenanceEventType, @coverage, @level, and @physDescStructuredType

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#26]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [x] Schema issue
- [x] Tag Library issue
- [x] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: The change suggested in this issue relates to the general feature request in #1. Out of the attributes that currently work with predefined values lists in the schema, eight are defined as mandatory at the moment within their contexts and it is suggested to make them optional. This would be a sensible action in order not to have to require the related `@...Encoding` attributes within `<control>`, even if the relevant attribute in the description section might actually not be used.

**_Note for working on and testing this issue: When the schema changes are done in the respective development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list by ticking the box._**

- [x] **Make attributes in the control section optional (for EAD and EAC-CPF)**
_Reasoning: If these attributes are kept mandatory, the related `@...Encoding` attributes have to be mandatory, too, which would also require them to come with a default value (either "EASList" or "other...Encoding"). However, within a single institution, especially when the EAD results from an export of a Collection Management System (CMS), those elements and attributes might more often than not be filled with default texts, simply because they have to be there to create a valid EAD file, but not because this is information that would be available in the CMS or would be required for internal processes. Similarly it might be questionable that someone hand-coding in EAD will continuously update those elements and attributes with each editing step. And in the context of aggregation services, it might rather be other parts of <control> that are of interest or it might actually be more useful to have descriptive information in the elements rather than predefined values in the attributes._ 
  - [x] `@maintenanceStatus`
  - [x] `@maintenanceEventType`
- [x] **Make attributes in the description section optional (only for EAD)**
_Reasoning: If these attributes are kept mandatory, the related `@...Encoding` attributes have to be mandatory, too, just in case, even though - overall - the elements in which these attributes are used are not required for a valid EAD file._ 
  - [x] `@coverage`
  - [x] `@physDescStructuredType`
_Reasoning: Same as for the previous two attributes._ 
- [x] Make attribute `@level` within `<archDesc>` optional **(only for EAD)**
_Reasoning: While TS-EAS acknowledges the importance of assigning levels - or, to speak with RiC, types - especially to record sets, the aspect of requiring this is questioned. Especially as the requirement only (can) refer(s) to <archDesc>, but not to <c> elements, which are optional within EAD overall, i.e. the same reasoning as for the previous four attributes would apply._

**Comment by kerstarno** [comment]
TS-EAS discussed this issue at the EAD revision meeting in Washington, DC, on 24 July and decided to move forward with changing the occurrence of the attributes as suggested in the (extended) description of this issue. Especially for changing `@level` it was agreed that this will benefit significantly from a more general reasoning provided as part of e.g. revision notes when publishing the draft and final versions of EAD 4.0.

**Comment by kerstarno** [comment]
Update (4 January 2024):

Following the EAD team's meeting on 15 December and in relation to the changes suggested with #33, #58, and #65 regarding the type attributes for agents, target entities, and digital archival objects, the details of this issue have been updated. The current development version of the schema might still represent what was outlined initially, i.e. also referring to the attributes `@agentType`, `@targetType`, and `@daoType`, but these attributes have now been changed to elements or will be dealt with in different ways, so should not be included in this issue here anymore.

**Comment by fordmadox** [comment]
I *think* this is ready to test.  Just let me know what else needs to be addressed.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that the occurrence of these attributes has been changed to being optional.
