### ISSUE TITLE
Add option to include attributes from any other namespace to all elements of EAD

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#28]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 
- [x] Add the option to include attributes from any other namespace to all elements of EAD. Additional namespaces would need to be declared. Attributes from such namespace could then be used in all appropriate places of an EAD XML file. 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please add a comment to this issue; once the changes have been tested successfully please mark this by ticking the box.**_

**Comment by fordmadox** [comment]
Already allowed.  However, like EAC, this option is not currently permitted on the document-level element (i.e. 'ead')

**Comment by kerstarno** [comment]
Tested with XSD and RNG. In both, there are two elements that currently do not include the option to include attributes from any other namespaces:

- `<colspec>`, though this will be removed anyway as a result of #62 
- `<ead>`, contrary to the comment above from 17 July 2023, EAC-CPF 2.0 does allow this option in the root element `<eac>`, so this should be the same in EAD 
  - In extension to the above: `<ead>` is missing all attributes in the EAD 4.0 development schemas; it should include `@audience`, `@id`, `@languageOfElement`, `@scriptOfElement`, and `@base`, same as `<eac>` does in EAC-CPF 2.0

**Comment by fordmadox** [comment]
Thanks.  I had completely misread the source file back in July.  The EAD and EAC document node definitions should include the same attributes now.  'colspec' is still around, but will be gone soon.

**Comment by kerstarno** [comment]
Re-tested with the XSD and RNG and can confirm that now also `<ead>` includes the option to add attributes from any other namespace. `<colspec>` has been removed in the meantime.
