### ISSUE TITLE
Placeholder preparing for the next major revision - Review the use of <localControl>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eas-schemas#3]
## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Review the use of `<localcontrol>`, see use cases in Aug 2020 in @fordmadox [comment ](https://github.com/SAA-SDT/eac-cpf-schema/issues/105#issuecomment-671461313) for EAC.

## Reporting a bug

* Text:

## Suggested Solution

* Text: Mark wrote:

> None of those examples associate date information with one of the local "terms", and all of the examples would be better accommodated [...] via an attribute in another namespace, since they are all there, by definition, for local use.

## Context

* Text: In EAC this element is only used to encode the level of detail according ISAAR(CPF). This can easily be solved by the introduction of an attribute `//control @levelOfDetail` with a list of values. EAC has minimal interest to keep this element but will have it for alignment of `//control`.

**Comment by kerstarno** [comment]
This issue is superseded by #32.
