### ISSUE TITLE
Add @target to all elements except <ead>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#31]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Add `@target` to all elements except for `<ead>` (change from only being used with `<ptr>` and `<ref>`).

- [x] Add `@target` to all elements except for `<ead>`
- [x] Change data type from IDREF to IDREFS

_**Note for working on and testing this issue: When the schema changes are done in development branch, please add a comment to this issue; once the changes have been tested successfully please mark this by ticking the box.**_

**Comment by fordmadox** [comment]
Ready for testing.

**Comment by karinbredenberg** [comment]
@target is present on all elements except the ead-element and its possible to have more than one id being referenced.
