### ISSUE TITLE
Transform all text-formatting attributes to @style

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#35]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [x] Schema issue
- [x] Tag Library issue
- [x] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: For alignment with EAC-CPF, it is suggested to transform all formatting attributes to `@style` and to recommend this attribute's usage with the appropriate CSS properties instead of listing a selection of these as predefined values in the schema.

**Update (4 January 2024):
Following the EAD team's meeting on 15 December and in relation to the change suggested with #62 and #63 , the details of this issue have been updated.**

**_Note for working on and testing this issue: When the schema changes are done in the respective development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list by ticking the box._**

- [x] Add `@style` with data type normalizedString to EAD
- [x] **Replace the following attributes with `@style`**
  - [x] ~~`@align` in `<tgroup>`, `<colspec`, and `<entry>`~~
  - [x] ~~`@colsep` in `<table>`, `<tgroup>`, `<colspec`, and `<entry>`~~
  - [x] ~~`@frame` in `<table>`~~
  - [x] ~~`@pgwide` in `<table>`~~
  - [x] ~~`@rowsep` in `<table>`, `<tgroup>`, `<colspec`, `<row>` and `<entry>`~~
  - [x] ~~`@valign` in `<tgroup>`, `<colspec`, and `<entry>`~~
  - [x] ~~`@listType`, `@mark`, and `@numeration` in `<list>`~~
  - [x] `@render` in ~~`<titleproper>` (which will be replaced by `<title>`, see #27),~~ `<title>` ~~, `<emph>`, `<foreign>`, and `<quote>`~~

In EAC-CPF, this means to:
- [ ] Remove `@listType` from `<list>`, which already includes `@style` in EAC-CPF

**Comment by fordmadox** [comment]
Still need to update "table" and the other elements, if we're keeping those in the base EAD schemas.

**Comment by kerstarno** [comment]
With the suggested change on `<formattingExtension>` (#62), the changes initially mentioned here for `<table>` and its sub-elements are obsolete. 

The description of this issue has been updated accordingly and the issue has been labelled as "Ready for testing". 

@marieelia - the change mentioned above with regard to EAC-CPF would only apply initially. Should EAC-CPF follow EAD in the approach with `<formattingExtension>`, that change would incorporate the change mentioned here re `@listType` anyways.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that `@style` has been added with the data type normalizedString. Most of the affected attributes have been removed in the context of #62. However, the change from `@render` to `@style` for `<title>` is currently missing. While `@render` has indeed been removed from `<title>`, `@style` has not yet been added. 

I have NOT created a new pull request for this, but have added the change to the branch "issue_62_63" to avoid interferences when merging. Once merged, this issue needs another round of testing.

**Comment by kerstarno** [comment]
Re-tested with the XSD and the RNG and can confirm that `@style` is now available with `<title>`.
