### ISSUE TITLE
Remove display attributes from EAD (following up from change to @style in issue #35)

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#36]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: With the change towards `@style`, which will allow for any possible CSS properties as values (see #35), the attributes `@altrender` and `@label` to specify alternative rendering or labels for certain elements should be removed as well.   

**_Note for working on and testing this issue: When the schema changes are done in development branch, please add a comment to this issue; once the changes have been tested successfully please mark this by ticking the box._**

- [x] Remove `@altrender` from the attribute group am.common.empty
- [x] Remove `@label` from `<abstract>`, `<container>`, ~~`<dao>` and `<daoSet>`~~ (already taken care of in the context of integrating with `<formAvailable>`),  ~~`<identificationDataNote>`~~ (already taken care of in the context of aligning this element with `<descriptiveNote>`), `<languageOfMaterial>`, `<materialSpec>`, `<physDesc>`, `<physDescStructured>`, `<physDescSet>`, `<physLoc>`, ~~`<origination>` and `<repository>`~~ (already taken care of in the context of integrating with `<agent>`),  `<unitDate>`, `<unitDateStructured>`, `<unitId>`, `<unitTitle>`, `<language>`, and `<writingSystem>`

**Comment by fordmadox** [comment]
Easily done, since never added to the new schema pipeline.  

However, any EAD2002/3 transformation will likely need to move these attributes to attributes in a separate namespace (e.g.  legacy:altrender="whatever").  Most uses of this attribute in the wild have little to do with CSS-like formatting declarations.

**Comment by kerstarno** [comment]
Thanks, Mark. And, yes, we probably need to have a look at these attributes and see if we can provide transformation guidelines for anything we wouldn't be able to cover in a predefined transformation. E.g. "If you've use `@altrender` to provide alternative styling information, transform to `@style`. If you have used `@altrender` in any other way, consider using the option to include attributes from any other namespace to keep its intended purpose."  

As a note, but we can discuss later how to best do this: this issue was meant for the EAD Schema (simple) - see label -, which would be one of the alternative schemas to discuss at the Washington meeting - see milestone. I.e. the EAD Schema (general) should, for now, still have `@altrender`, while it should be removed in the EAD Schema (simple).

**Comment by kerstarno** [comment]
TS-EAS has decided to move forward with this issue when discussing it at the EAD revision meeting in Washington, DC, on 24 July 2023.

**Comment by kerstarno** [comment]
Tested successfully. Neither the XSD nor the RNG include `@altrender` anymore. 

If defining rendering/formatting/display information for any element in EAD 4.0 is considered necessary, the new option of including attributes from other namespaces to do so, is recommended. Ideally, however, rendering/formatting/display should be dealt with via a CSS rather than encoding in EAD. 

If `@altrender` was used for other purposes than the intended alternative rendering in EAD 2002 or EAD3, the new option of including attributes from other namespaces is expected to allow for more precise encoding.
