### ISSUE TITLE
Remove @relatedencoding and @encodinganalog from EAD

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#37]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Remove `@relatedencoding` and `@encodinganalog`    

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box._**

- [x] **Remove `@relatedencoding` from**
  - [x] `<ead>`
  - [x] `<control>`
  - [x] `<archDesc>`
- [x] **Remove `@encodinganalog` from**
  - [ ] Most of the current EAD elements 
  (elements that don't include `@encodinganalog` in EAD3 are `<ead>`, `<indexentry>`, `<namegrp>`, `<ptrgrp>`, `<geographiccoordinates>`, `<p>`, `<blockquote>`, `<chronitem>`, `<chronitemset>`, `<event>`, `<list>`, `<defitem>`, `<label>`, `<item>`, `<listhead>`, `<head01>`, `<head02>`, `<head03>`, `<table>`, `<tgroup>`, `<colspec>`, `<tbody>`, `<row>`, `<entry>`, `<thead>`, `<address>`, `<addressline>`, `<footnote>`, `<head>`, `<datesingle>` which will be removed, see #4 , `<daterange>`, `<fromdate>`, `<todate>`, `<dateset>`, `<abbr>`, `<emph>`, `<expan>`, `<foreign>`, `<lb>`, `<quote>`, `<ptr>`, `<ref>`, and `<objectxmlwrap>`)

**Comment by kerstarno** [comment]
Thanks, Mark. As a note, but we can discuss later how to best do this: this issue was meant for the EAD Schema (optional attributes) - see label -, which would be one of the alternative schemas to discuss at the Washington meeting - see milestone. I.e. the EAD Schema (general) should, for now, still have `@relatedEncoding` and `@encodingAnalog`, while it should be removed in the EAD Schema (optional attributes).

**Comment by MicheleCombs** [comment]
The encodinganalog attribute is essential for generating an accurate MARC record from EAD.  I'm puzzled as to the rationale for removing it?  Perhaps I am misunderstanding something.

**Comment by kerstarno** [comment]
Thanks for the feedback, Michele. Again (see labelling), this issue is currently only up for review. 

Could you maybe provide some more details about the technical process applied to generate MARC from EAD in your case and how the `@encodingAnalog` attribute would be a required element of this? If this is based on an XSLT, I'd have thought it would be possible to simply do such transformation based on the EAD element without requiring `@encodingAnalog` to be present.

**Comment by MicheleCombs** [comment]
We use marcedit to generate an .mrc file which we then send to Cataloging for import into Voyager and OCLC.  The marcedit XSL uses the encodinganalog attribute at several points, such as to distinguish between inclusive vs bulk dates (245$g vs 245$f), and to distinguish between 6xx and 7xx marc fields for controlaccess child elements.

**Comment by fordmadox** [comment]
Example, from MarcEdit: https://github.com/reeset/marcedit_xslt_files/blob/master/EADAnalyticstoMARC21slimXML.xsl#L82C74-L82C79

**Comment by kerstarno** [comment]
The EAD team reviewed this issue during their meeting in Washington on 26 July 2023 and confirmed the intended removal of these two attributes. Instead, the new vocabulary attributes (`@valueURI`, `@vobacularySource` and `@vocabularySourceURI`) will be available with most of the elements currently using `@encodinganalog`. In these cases, `@vocabularySource` could name e.g. MARC as the related standard while `@valueURI` would hold the respective field numbers.

The EAD team also had a look at the MarcEdit XSLT from EAD 2002 as linked above. In this XSLT, it seems that the `@encodinganalog` attribute is only relevant in cases where the same EAD element could be mapped to more than one MARC field. For cases, where there is a one-to-one relation between EAD element and MARC field, the element in itself is sufficient to make the conversion work.

**Comment by kerstarno** [comment]
Tested with the XSD and RNG. While `@relatedencoding` does not exist anymore, `@encodingAnalog` still is included in 13 elements:

- `<bibliography>` (to be renamed to `<publicationNote>`)
- `<container>`
- `<dao>` (to be integrated in the new element `<formAvailable>`, see #65)
- `<langMaterial>` (to be renamed to `<languageOfMaterial>`)
- `<languageSet>`
- `<origination>` (to be integrated with the extended `<agent>` element, see #58)
- `<otherFindAid>`
- `<relatedMaterial>`
- `<separatedMaterial>`
- `<unitDate>`
- `<unitDateStructured>`
- `<unitId>`
- `<unitTitle>`

As mentioned in a previous comment, these as well as other elements currently allowing for `@encodinganalog` in EAD3 will allow for the vocabulary attributes for pointing to related standards that represent the element's content as part of their code or term lists instead.

**Comment by fordmadox** [comment]
Ready for testing again

**Comment by kerstarno** [comment]
Re-tested with the XSD and the RNG and can confirm that the attribute `@encodinganalog` has now also been removed from the remaining elements commented above.
