### ISSUE TITLE
Remove @lastdatetimeverified from EAD

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#39]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Remove `@lastdatetimeverified`    

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box._**

- [x] **Remove `@lastdatetimeverified` from**
  - [x] `<source>` (aligned with EAC-CPF, see #32)
  - [x] `<relation>` (aligned with EAC-CPF, see #33)

**Comment by fordmadox** [comment]
Tests look great in both schemas.
