### ISSUE TITLE
Integrate <archref> and <bibref> with <reference>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#46]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Remove `<archref>` and `<bibref>` from EAD. There is currently no difference between `<archref>`, `<bibref>`, and `<ref>` apart from the circumstance that the latter cannot include itself. On the other hand, `<ref>` includes linking attributes, which `<archref>` and `<bibref>` don't allow for. `<archref>` and `<bibref>` are currently available as direct sub-elements of `<bibliography>` (where archival references might not be used that often, but the context indicates references to be of a bibliographic type) and `<otherfindaid>`, `<relatedmaterial>`, and `<separatedmaterial>` (where bibliographic references might not be used that often, but the context indicates references to be of a archival type). In all four of these parent elements, `<ref>` (now `<reference>`, see #40) would be available within `<p>`, `<item>`, `<entry>`, and `<event>` as an alternative.

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower and intermediate (printed in italics) levels._**

- [x] **Remove `<archref>` from**
  - [x] ~~`<bibliography>`~~ renamed to `<publicationNote>`
  - [x] `<otherFindAid>`
  - [x] `<relatedMaterial>`
  - [x] `<separatedMaterial>`
- [x] **Remove `<bibref>` from**
  - [x] ~~`<bibliography>`~~ renamed to `<publicationNote>`
  - [x] `<otherFindAid>`
  - [x] `<relatedMaterial>`
  - [x] `<separatedMaterial>`

**Comment by MicheleCombs** [comment]
Not sure where this request came from, but archref is really useful to us.  We use it to reference other of our archival collections within relatedmaterial.  This allows us to use an abbreviated URL (i.e. just the file name) and then, based on the fact that it's an archref, automatically generate the correct prefix.  This is super helpful since sometimes our finding aids get moved en masse, and we have to alter the path to them,  This would be much harder to do with just extref (which technically isn't the correct element, since these are not external references, they are references within our repository/institution).  So, it would be nice if we could keep archref.

**Comment by kerstarno** [comment]
Thanks for the feedback, Michele. It's always good to have real-world examples. I'd think it would be possible to do what you described also with `<reference>` as the context of `<relatedMaterial>` would already indicate that these are archival references, but for now this issue is only up for review (see labelling) and not decided yet. :-)

**Comment by MicheleCombs** [comment]
Not necessarily -- we also sometimes include, in relatedmaterial, links to resources that are _not_ our own archival collections.  It might be an archival collection at another repository, or a website, or a digital collection, and so on.  Thus we would not be able to assume that all references within relatedmaterial would be archrefs.

**Comment by MicheleCombs** [comment]
Sure!  Take a look at [the Related Materials section of our Grove Press finding aid](https://library.syracuse.edu/digital/guides/g/grove_press.htm#relatedmatlink ).

**Comment by MicheleCombs** [comment]
Sure - you can find the ead code for all our finding aids here https://library.syracuse.edu/ead/xml/    This one is grove_press.xml

**Comment by kerstarno** [comment]
As a note to be taken into account during the further review of this issue: 

The example of the Syracuse University finding aid uses EAD 2002 (DTD). With regard to `<archref>` and `<bibref>` this highlights a main difference between EAD 2002 and EAD3, as in EAD3 neither of these two elements allows for linking attributes anymore. One would need to apply the following encoding to get to the same effect, which already requires the use of `<ref>` in order to include links. Same for `<extref>`, which doesn't exist in EAD3 anymore.
```
<relatedmaterial>
  <head>Related Material</head>
  <p>For additional material related to Grove Press, see also the following: 
    <list>
      <item>
        <!-- <arch --><ref href="wainhouse_a.htm">Austryn Wainhouse Papers<!-- </arch --></ref>
      </item>
      <item>
        <!-- <arch --><ref href="glass_int.htm">Loren Glass Interviews Relating to Grove Press<!-- </arch --></ref>
      </item>
      <item>
        <!-- <arch --><ref href="deardoff.htm">Kenneth Deardoff Collection Relating to Grove Press<!-- </arch --></ref>
      </item>
      <item>
        <!-- <arch --><ref href="prix.htm">Prix Formentor Collection<!-- </arch --></ref>, which contains materials about the Prix International and Prix Formentor literary prizes.
      </item>
      <item>
        <!-- <arch --><ref href="creative.htm">Creative Film Foundation Records<!-- </arch --></ref>
      </item>
    </list>
  </p>
  <p>
    <!-- <ext --><ref href="http://findingaids.cul.columbia.edu/ead/nnc-rb/ldpd_7953908/summary">Barney Rosset's personal papers<!-- </ext --></ref> are housed at the Columbia University Rare Book and Manuscript Library, which also has a small <!-- <arch --><ref href="http://findingaids.cul.columbia.edu/ead/nnc-rb/ldpd_10553502/summary">Grove Press Collection<!-- </arch --></ref>.
  </p>
</relatedmaterial>
```

**Comment by kerstarno** [comment]
During their meeting in Washington on 26 July 2023, the EAD sub-team decided to move forward with this change. In addition to `<reference>` opening up the option of linking again, which EAD3 had removed from `<archref>` and `<bibref>`, the content model of those elements currently including `<archref>` and `<bibref>` in EAD3 also will be extended (see #69) by enabling `<relations>` as a direct sub-element of `<otherFindAid>`, `<publicationNote>` (renamed from `<bibliography>`), `<relatedMaterial>`, and `<separatedMaterial>`. The respective sub-elements that become available with this will allow for a more explicit description as well as categorisation/typing of the related materials referenced than was possible so far.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that this has been implemented as expected. The four elements in question now also include the `<relations>` element, which would allow for detailing various types of related materials/resources that one might want to reference in these elements.
