### ISSUE TITLE
Apply camelCase spelling to EAD

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#49]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Shared elements and attributes (including their values) will have camelCase spelling. To avoid different approaches to spelling the (tag) names of elements and attributes EAD, camelCase spelling is to be applied across all elements and attributes therein.

**Update (8 January 2024):
Following the EAD team's meeting on 15 December, the details of this issue have been updated to the latest status. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

- [x] **Adapt the following element (tag) names to camelCase spelling**
  - [x] acqInfo -> sourceOfAcquisition
  - [x] addressLine
  - [x] agencyCode
  - [x] agencyName
  - [ ] ~~altFormAvail~~ (see #65)
  - [x] archDesc
  - [ ] ~~archRef~~ (see #46) 
  - [ ] ~~bibRef~~ (see #46)
  - [x] biogHist
  - [ ] ~~blockQuote~~ (see #62)
  - [ ] ~~chronItem~~ (see #62)
  - [ ] ~~chronItemSet~~ (see #62)
  - [ ] ~~chronList~~ (see #62)
  - [ ] ~~colSpec~~ (see #62)
  - [ ] ~~controlAccess~~ (see #67)
  - [x] conventionDeclaration
  - [ ] ~~corpName~~ (see #58, #63)
  - [x] custodHist
  - [ ] ~~daoSet~~ (see #65)
  - [x] dateRange
  - [x] dateSet
  - [ ] ~~defItem~~ (see #62)
  - [x] descriptiveNote
  - [x] didNote -> identificationDataNote
  - [x] eventDateTime
  - [x] eventDescription
  - [ ] ~~famName~~ (see #58, #63)
  - [x] filePlan
  - [x] fromDate
  - [ ] ~~genreForm~~ (see #63, #67)
  - [x] geographicCoordinates
  - [ ] ~~indexEntry~~ (see #67)
  - [x] langMaterial -> languageOfMaterial
  - [x] languageDeclaration
  - [x] languageSet
  - [x] legalStatus
  - [ ] ~~listHead~~ (see #62)
  - [x] localTypeDeclaration
  - [x] maintenanceAgency
  - [x] maintenanceEvent
  - [x] maintenanceHistory
  - [x] materialSpec
  - [ ] ~~nameGrp~~ (see #67)
  - [x] objectXMLWrap
  - [ ] ~~originalsLoc~~ (see #65)
  - [x] otherAgencyCode
  - [x] otherFindAid
  - [x] otherRecordId
  - [ ] ~~persName~~ (see #58, #63)
  - [x] physDesc
  - [x] physDescSet
  - [x] physDescStructured
  - [x] physFacet
  - [x] physLoc
  - [x] physTech -> physicalOrTechnicalRequirements
  - [x] preferCite
  - [x] processInfo
  - [ ] ~~ptrGrp~~ (see #67)
  - [x] recordId
  - [x] relatedMaterial
  - [x] rightsDeclaration
  - [x] scopeContent
  - [x] separatedMaterial
  - [ ] ~~tBody~~ (see #62)
  - [ ] ~~tGroup~~ (see #62)
  - [ ] ~~tHead~~ (see #62)
  - [x] toDate
  - [x] unitDate
  - [x] unitDateStructured
  - [x] unitId
  - [x] unitTitle
  - [x] unitType
- [x] **Adapt the following attribute (tag) names to camelCase spelling**
  - [ ] ~~altHead~~ (see #44)
  - [ ] ~~altRender~~ (see #36) 
  - [ ] ~~charOff~~ (see #62)
  - [ ] ~~colName~~ (see #62)
  - [ ] ~~colNum~~ (see #62)
  - [ ] ~~colWidth~~ (see #62)
  - [x] containerId
  - [x] coordinateSystem
  - [x] countryCode
  - [x] countryEncoding
  - [ ] ~~daoType~~ (see #65)
  - [x] dateChar
  - [x] dateEncoding
  - [x] dscType -> descriptionOfComponentsType
  - [ ] ~~encodingAnalog~~ (see #37)
  - [ ] ~~entityRef~~ (see #45) 
  - [x] languageCode
  - [x] languageEncoding
  - [x] linkRole
  - [x] linkTitle
  - [x] localType
  - [ ] ~~moreRows~~ (see #62)
  - [ ] ~~nameEnd~~ (see #62)
  - [ ] ~~nameSt~~ (see #62)
  - [x] notAfter
  - [x] notBefore
  - [x] physDescStructuredType
  - [ ] ~~relatedEncoding~~ (see #37)
  - [x] repositoryCode
  - [x] repositoryEncoding
  - [x] scriptCode
  - [x] scriptEncoding
  - [x] standardDate
  - [x] standardDateTime
  - [x] unitDateType
  - [ ] ~~xPointer~~ (see #45)
- [x] **Adapt the following attribute values to camelCase spelling**
  - [x] otherLanguageEncoding
  - [x] otherScriptEncoding
  - [x] otherDateEncoding
  - [x] otherCountryEncoding
  - [x] otherRepositoryEncoding

**Comment by fordmadox** [comment]
Hold on this until there's an update about formatting elements (e.g. blockquote).

**Comment by fordmadox** [comment]
Still a lot to review and update, e.g. "xpointer".

**Comment by fordmadox** [comment]
Hold until we hear more from Kerstin based on discussion from 2023-12-15 EAD meeting.

**Comment by kerstarno** [comment]
Updated to latest status.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that all the above elements, attributes, and attribute values are now used with camelCase spelling. The only pending exception is the change from `<langMaterial>` to `<languageOfMaterial>`. As this is already reported in #66 (and taken care of with #81), I will mark this issue here as "Tested successfully".
