### ISSUE TITLE
Vocabulary attributes in sub-elements of <did>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#51]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: As a follow-up to #13, this issue relates to the current use of vocabulary attributes in sub-elements of <did>.

**Update (8 January 2024):
Following the EAD team's meeting on 15 December, the details of this issue have been updated to the latest status. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

- [x] **`<unitTitle>`** (_currently includes `@normal` which is removed in other contexts with the argument that providing a `@valueURI` plus, ideally, a `@vocabularySource` or `@vocabularySourceURI` will allow to retrieve a normalised form of the relevant element's content without the necessity to have this encoded specifically in EAD; `<unitTitle>`, however, does not include any other vocabulary attributes at the moment_)
  - [x] Remove `@normal` from `<unitTitle>`
  - [x] Add `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI` to `<unitTitle>` (which would then have similar attributes as `<title>`)
  - [ ] Note for conversion: `@normal` would be transformed into `@valueURI`, which might require a check that the value (from `@normal`, which is of data type token) doesn't violate the data type anyURI
- [x] **~~`<dao>` and~~ `<unitId>`** (_currently include `@identifier` which is replaced by `@valueURI`, see #13;  `@valueURI` always comes in combination with `@vocabularySource` and `@vocabularySourceURI`, which do not exist in ~~`<dao>` and~~ `<unitId>` yet_)
  - [x] Replace `@identifier` with `@valueURI` in ~~`<dao>` and~~ `<unitId>`
  - [x] Add `@vocabularySource` and `@vocabularySourceURI` to ~~`<dao>` and~~ `<unitId>`

_Notes_
- `@normal` in `<date>` is dealt with as part of the alignment of encoding dates (see #4)

**Comment by kerstarno** [comment]
TS-EAS has decided to move forward with this issue when discussing it at the EAD revision meeting in Washington, DC, on 24 July 2023.

**Comment by fordmadox** [comment]
Is there a separate ticket for "dao" and "daoSet"?  This ticket is not ready for testing, so let's discuss during the 2023-12-15 meeting.

**Comment by kerstarno** [comment]
Tested with XSD and RNG and can confirm that this is implemented as expected.
