### ISSUE TITLE
Remove deprecated attributes and elements

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#52]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Deprecated attributes and elements should be removed following their deprecation in EAD3, equalling the announcement that they'll be removed in the next version (i.e. EAD 4.0). ~~This excludes the element `<div>` which will be reinstated within `<findAidDesc>` (see #27)~~.

**Update (8 January 2024):
Following the EAD team's meeting on 15 December and in relation to #62, the details of this issue have been updated. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box on the higher level of the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower levels of the list and - if applicable - the intermediate levels (printed in italics)._**

- [x] **Remove deprecated attributes**
  - [x] `@placement` in `<runner>` (also deprecated)
  - [x] `@tpattern` in `<c>` and `<c01>` to `<c12>`
- [x] **Remove deprecated elements**
  - [x]  `<bibseries>` in `<bibRef>`, `<unitTitle>`, and (the also deprecated) `<titlepage>`
  - [x] `<descgrp>` in `<archDesc>`, `<c>`, and `<c01>` to `<c12>`
  - [x] Updated (8 January 2024): `<div>` in `<frontmatter>` (also deprecated)
  - [x] `<extent>` in `<physDesc>`
  - [x] `<frontmatter>` in `<ead>`
  - [x] `<imprint>` in `<bibRef>` and `<unitTitle>`
  - [x] `<runner>` in `<archDesc>`
  - [x] `<titlepage>` in `<frontmatter>` (also deprecated)

**Comment by fordmadox** [comment]
Ready for testing.
