### ISSUE TITLE
Review abbreviated element names

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#53]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: In the context of applying camelCase spelling to EAD (#49), abbreviated element and attribute names should be reviewed and potentially be spelled out.

**Update (8 January 2024):
Following the EAD team's meeting on 15 December, the details of this issue have been updated to the latest status. Remaining list of elements is shown in a clean version at the top; complete list with change tracking and comments at the bottom. See also #66 for a short list of name changes resulting from the context here). 
The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing. The EAD sub-team members still have until Wednesday, 10 January, for final comments. Once this deadline has passed, the list below will be updated accordingly and a comment will be added confirming the final status ahead of the first draft.**

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

### New list (8 January 2024)
- [x] **Change the following abbreviated element (tag) names**
  - [x] acqInfo -> sourceOfAcquisition
  - [x] did -> identificationData
  - [x] didNote -> identificationDataNote
  - [x] dsc -> descriptionOfComponents
  - [x] langMaterial -> languageOfMaterial
  - [x] odd -> otherDescriptiveInfo 
  - [x] physTech -> physicalOrTechnicalRequirements
- [x] **Change the following abbreviated attribute (tag) names**
  - [x] dscType -> descriptionOfComponentsType

### Initial list (only for reference)
- **Review the following abbreviated element (tag) names**
  - abbr -> ~~abbreviation~~ see #48 and #63
  - acqInfo -> ~~acquisitionInformation~~ sourceOfAcquisition (to align with terminology used in DACS and ISAD(G)
  - altFormAvail -> ~~alternativeFormAvailable (if kept)~~ will be integrated with the new `<formAvailable>` element (#65)
  - archDesc -> ~~archivalDescription~~ no change with the same argument as used during the EAC-CPF revision re e.g. `<biogHist>`, i.e. the element name, while being abbreviated, still being easily understandable and having been well established with previous versions
  - biogHist -> ~~biographyOrHistory~~ no change (same argument as for `<archDesc>`)
  - c -> ~~component (also for numbered `<c>` elements; _if `<c>` elements were renamed, it might be worth considering if a new name closer to RiC could be useful, e.g. `<recordResource>`_)~~ no change (same argument as for `<archDesc>`)
  - chronItem -> ~~chronologyListItem (would also affect EAC-CPF)~~ no change (same argument as for `<archDesc>`); see also #62 
  - chronItemSet -> ~~chronologyItemSet or _chronologyListItemSet_ (would also affect EAC-CPF)~~ no change (same argument as for `<archDesc>`); see also #62
  - chronList -> ~~chronologyList (would also affect EAC-CPF)~~ no change (same argument as for `<archDesc>`); see also #62
  - colSpec -> ~~columnSpecification~~ will be removed as a result of #62 
  - controlAccess -> ~~controllAccess or _controlledAccess_~~ will be integrated with the new `<subjectHeadings>` element (#67)
  - corpName -> ~~corporateName~~ will be integrated with the extended `<agent>` element (#58); see also #63
  - custodHist -> ~~custodialHistory~~ no change (same argument as for `<archDesc>`)
  - dao -> ~~digitalArchivalObject~~ will be integrated with the new `<formAvailable>` element (#65)
  - daoSet -> ~~digitalArchivalObjectSet~~ same as for `<dao>`
  - did -> ~~descriptiveIdentification~~ identificationData
  - didNote -> ~~descriptiveIdentificationNote~~ identificationDataNote
  - dsc -> ~~subcomponentsDescription~~ descriptionOfComponents
  - emph -> ~~emphasis~~ will be replaced by `<span>` (#71)
  - expan -> ~~expansion~~ see #48 and #63
  - famName -> ~~familyName~~ will be integrated with the extended `<agent>` element (#58); see also #63
  - genreForm -> ~~genreForm or _genreOrForm_~~ see #63 and #67
  - langMaterial -> languageOfMaterial (to be aligned with the renaming of `@languageOfElement`, `@languageCode`, etc.
  - lb -> ~~lineBreak~~ see #47, #62, #70, and #71
  - materialSpec -> ~~materialSpecificDetails~~ no change (same argument as for `<archDesc>`)
  - nameGrp -> ~~nameSet~~ will be integrated with the new element `<subjectHeadings>` (#67)
  - num -> ~~number~~ see #63
  - odd -> ~~otherDescriptiveData~~ otherDescriptiveInfo _("info" is not resolved with the understanding that this abbreviation is internationally recognisable)_
  - originalsLoc -> ~~originalsLocation~~ will be integrated with the new `<formAvailable>` element (#65)
  - otherFindAid -> ~~otherFindingAid~~ no change (same argument as for `<archDesc>`)
  - p -> ~~paragraph~~ no change (same argument as for `<archDesc>`)
  - persName -> ~~personName or _personalName_~~ will be integrated with the extended `<agent>` element (#58); see also #63
  - physDesc -> ~~physicalDescription~~ no change (same argument as for `<archDesc>`)
  - physDescSet -> ~~physicalDescriptionSet~~ no change (same argument as for `<archDesc>`)
  - physDescStructured  -> ~~structuredPhysicalDescription or _physicalDescriptionStructured_ (?)~~ no change (same argument as for `<archDesc>`)
  - physFacet -> ~~physicalFacet~~ no change (same argument as for `<archDesc>`)
  - physLoc -> ~~physicalLocation~~ no change (same argument as for `<archDesc>`)
  - physTech -> ~~physicalAndTechnicalRequirements~~ physicalOrTechnicalRequirements
  - preferCite -> ~~preferredCitation~~ no change (same argument as for `<archDesc>`)
  - processInfo -> ~~processingInformation~~ no change (same argument as for `<archDesc>`)
  - ptr -> ~~pointer~~ see #47, #62, #63, #70, and #71
  - ptrGrp -> ~~pointerSet~~ will be integrated with the new element `<subjectHeadings>` (#67)
  - scopeContent -> ~~scopeContent or _scopeAndContent_~~ no change (same argument as for `<archDesc>`)
  - tBody -> ~~tableBody~~ will be removed as a result of #62 
  - tGroup -> ~~tableGroup -> _tableSet_ (?)~~ will be removed as a result of #62 
  - tHead -> ~~tableHead~~ will be removed as a result of #62 
- **Review the following abbreviated attribute (tag) names**
  - abbr -> ~~abbreviatedForm~~ see #48 and #63
  - altHead -> ~~alternativeHead~~ see #44
  - altRender -> ~~alternativeRendering~~ see #36
  - char -> ~~character~~ will be removed as a result of #62 
  - charOff -> ~~characterOffset~~ will be removed as a result of #62 
  - colName -> ~~columnName~~ will be removed as a result of #62 
  - colNum -> ~~columnNumber~~ will be removed as a result of #62 
  - cols -> ~~columns~~ will be removed as a result of #62 
  - colWidth -> ~~columnWidth~~ will be removed as a result of #62 
  - daoType -> ~~digitalArchivalObjectType~~ will be removed as a result of #65 
  - dateChar -> ~~dateCharacterization~~ will be removed as a result of #62 
  - dscType -> ~~subcomponentsDescriptionType~~ descriptionOfComponentsType
  - expan -> ~~expandedForm or _fullForm_ (?)~~ see #48 and #63
  - _href -> ~~hypertextReference_ (???)~~ no change (same argument as for `<archDesc>`)
  - nameSt -> ~~nameStart~~ will be removed as a result of #62 
  - physDescStructuredType -> ~~structuredPhysicalDescriptionType or _physicalDescriptionStructuredType_ (?)~~ no change (same argument as for `<archDesc>`)

**Comment by SJagodzinski** [comment]
Same decision as for `<biogHist>` was made for `<chronItemSet>`, `<chronItem>` and `<chronList>` in the context of the major revision of EAC-CPF: a change of name was rejected based on the argument that the element and its meaning is well-known enough in the international community.

see also: [EAC #168](https://github.com/SAA-SDT/eac-cpf-schema/issues/168)

**Comment by kerstarno** [comment]
Additional note for reference: As `<otherFindAid>` remains with the abbreviated "find" instead of "finding" and as the abbreviation "desc" is kept in other contexts, the new element `<findAidDesc>` (#27) will be introduced with these abbreviations as well.

**Comment by fordmadox** [comment]
Note:  I'd still like to review the availability (and need) of a few elements, such as `num`... but I think the current draft reflects all the above changes.  Let me know what I still need to address, though.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that the above mentioned changes have been implemented. The only exception is `<langMaterial>`, which still needs to be changed to `<languageOfMaterial>`. As this is already reported in #66 (and was taken care of in the pull request #81), I will mark this issue here as "Tested successfully".

**Comment by kerstarno** [comment]
> Note: I'd still like to review the availability (and need) of a few elements, such as `num`... but I think the current draft reflects all the above changes. Let me know what I still need to address, though.

`<num>` has been removed (see #63) in the latest version of the src/modules files on development branch. Not yet generated into new version of the schemas, though.
