### ISSUE TITLE
Move <abstract> out of <did> and include in longer descriptive elements

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#57]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: This follows the use of `<abstract>` in `<biogHist>` in EAC-CPF.  

**Update (8 January 2024):
Following the EAD team's meeting on 15 December, the details of this issue have been updated to the latest status. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

- [x] **Remove `<abstract>` from `<did>`**
- [ ] **Add `<abstract>` as optional, not repeatable sub-element to**
  - [x] `<accessConditions>` (renamed from `<accessrestrict>`)
  - [x] `<accruals>`
  - [x] `<sourceOfAcquisition>` (renamed from `<acqinfo>`)
  - [x] ~~`<alternativeFormAvailable>` (renamed from `<altformavail>`)~~
  - [x] `<appraisal>`
  - [x] `<arrangement>`
  - [x] `<publicationNote>` (renamed from `<bibliography>`)
  - [x] `<biogHist>` (thereby aligned with EAC-CPF)
  - [ ] ~~`<controlAccess>` (or `<controlledAccess>` renamed from `<controlaccess>`)~~
  - [x] `<custodHist>`
  - [x] `<filePlan>`
  - [ ] ~~`<index>`~~
  - [x] ~~`<legalStatus>` (see #5)~~
  - [x] `<otherDescriptiveInfo>` (renamed from `<odd>`)
  - [x] ~~`<originalsLocation>` (renamed from `<originalsloc>`)~~
  - [x] `<otherFindAid>`
  - [x] `<physicalOrTechnicalRequirements>` (renamed from `<phystech>`)
  - [x] `<preferCite>`
  - [x] `<processInfo>`
  - [x] `<relatedMaterial>`
  - [x] `<scopeContent>`
  - [x] `<separatedMaterial>`
  - [x] `<useConditions>` (renamed from `<userestrict>`)

**Comment by fordmadox** [comment]
And would `<abstract/>` follow EAC's data model at this point? I'm assuming so, so I will add it that way to start, but if that's incorrect, just add a new checklist item to the ticket.

**Comment by kerstarno** [comment]
Ideally, yes. It would be decided together with `<p>`etc. (#47).

**Comment by karinbredenberg** [comment]
Renaming of elements is not implemented in all cases yet.
Removal of elements have not been implemented yet. These elements have in the cases of altFormAvail, legalStatus and orginalsLoc had the abstract element implemented.

The testing of implementation of abstract is thus ready.
