### ISSUE TITLE
Add a new element <referringString>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#63]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno 
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: During their meeting on 24 November 2023, the EAD subteam of TS-EAS suggested to introduce a new element called `<referringString>` to allow for the tagging of named entities within textual descriptions using one dedicated element instead of having a long list of mixed content elements to take into account. This would also allow for `<span>` to be more specifically used for formatting and highlighting aspects by using `@style` (as it has been in EAC-CPF all along).
* `<referringString>` should hence be added in all contexts that allow for `<span>`. _(status of this needs to be reviewed in the current (1 December 2023) draft schema for EAD 4.0)_
* **`<referringString>`**
  - [x] Can contain text
  - [x] Is optional and repeatable in all contexts
  - [x] Allows for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, and `@localTypeDeclarationReference`
  - [x] Allows for the optional attributes `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`
  - [x] Allows for the inclusion of attributes from any other namespaces

**Update (5 January 2024):
Following the EAD team's meeting on 15 December, the details of this issue have been updated to the latest status with the additions below this paragraph. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

Ultimately, the introduction of `<span>` (which replaces `<emph>`, see #71) and `<referringString>` along with the use of `<reference>` will lead to a minimal mixed content model in the EAD 4.0 general schema, which might be further reduced in the core schema.

- [x] **Replace `<abbr(eviation)>`, `<expan(sion)>`, and `<foreign>` with `<referringString>` in**
  - [x] `<container>`
  - [x] `<dimensions>`
  - [x] `<head>`
  - [x] `<materialSpec>`
  - [x] ~~`<num>`~~
  - [x] `<physDesc>`
  - [x] `<physFacet>`
  - [x] `<physLoc>`
  - [x] `<unitDate>`
  - [x] `<unitId>`
  - [x] `<unitTitle>`
- [x] **Combine `<ptr>`  with `<reference>` in**
  - [x] `<container>`
  - [x] `<dimensions>`
  - [x] `<head>`
  - [x] `<materialSpec>`
  - [x] ~~`<num>`~~
  - [x] `<physDesc>`
  - [x] `<physFacet>`
  - [x] `<physLoc>`
  - [x] `<unitDate>`
  - [x] `<unitId>`
  - [x] `<unitTitle>`
- [x] **Replace `<corpname>`, `<date>`,  `<famname>`, `<function>`, `<genreform>`, `<geogname>`, `<name>`, `<num>`, `<occupation>`, `<persname>`, `<subject>`, and `<title>` with `<referringString>` in**
  - [x] `<physFacet>`
  - [x] `<unitTitle>`
- [x] **Replace `<footnote>` and `<quote>` with `<span>` in**
  - [x] `<physFacet>`
  - [x] `<unitTitle>`
- [x] **Remove `<lb>` from**
  - [x] `<container>`
  - [x] `<dimensions>`
  - [x] `<head>`
  - [x] `<materialSpec>`
  - [x] ~~`<num>`~~
  - [x] `<physDesc>`
  - [x] `<physFacet>`
  - [x] `<physLoc>`
  - [x] `<unitDate>`
  - [x] `<unitId>`
  - [x] `<unitTitle>`
_For the replacement of `<emph>` with `<span>` in all the elements mentioned above see #71._

For `<identificationDataNote>` (was: `<didNote>`), which currently also includes the above mentioned sub-elements, a different approach is taken:
- [x] **Align the content model of `<identificationDataNote>` with the one of `<descriptiveNote>`**
  - [x] Remove `<abbr(eviation)>`, `<expan(sion)>`, `<foreign>`, `<ptr>`, `<ref>`, `<emph>` and `<lb>` from `<didNote>`
  - [x] Add `<p>` as required and repeatable sub-element instead
  - [x] Adapt `@audience`
  - [x] Add `@target` as an optional attribute
  - [x] Rename `@lang` to `@languageOfElement` and `@script` to `@scriptOfElement`
  - [x] Add the optional attributes `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`
  - [x] Add the option to include attributes from any other namespace
  - [x] Remove `@altrender`, `@localtype`, `@label`, and `@encodinganalog`

_For the alignment of the descriptive, shared elements `<abstract>`,`<reference>` (replacing `<ref>`, see #40), and `<p>` see #47._
_For the alignment of data-centric, shared elements such as `<addressLine>` or the single date elements in terms of mixed content see #70._

**Comment by fordmadox** [comment]
Kind of testable now at https://github.com/SAA-SDT/eas-schemas/tree/issue_63

Currently, "reference/span" is allowed, so "reference/referringString" is also permitted in the above branch.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG. 

Most of the above has been implemented as expected, apart from:

- `<head>` should still kept in EAD 4.0 for use within `<did>` and the numbered and unnumbered `<c>` elements, but has currently been removed; hence the changes here cannot be checked
- `<num>` should have been removed (apologies for the mixed messages in the original post)
- `@localType` is still included in `<identificationDataNote>`, but should be removed (same for `@localTypeDeclaration`)

I created a pull request for the above pending changes (#80). Once the pull request has been merged, this issue will need retesting.

**Comment by kerstarno** [comment]
> Sorry, I had thought that `head` was going away with a suggestion for folks to use h1-h6 in its place, so thanks for adding that back in. Should be ready for testing again now.

Thanks. And, yes, it's a bit confusing. `<head>` is only kept in those contexts where it wasn't used alongside the block formatting elements. In those contexts, where `<head>` went side-by-side with `<p>`, `<list>`, etc. it's been removed as it would be taken care of by using `<h1>` etc. within `<formattingExtension>`.

**Comment by kerstarno** [comment]
Re-tested with the XSD and RNG and can confirm that the remaining changes have now been implemented as expected.

**Comment by florenceclavaud** [comment]
Hi everybody, what about adding to the new `referringString` element an attribute to specify the kind of relation that exists between the records described and the entity that is referred to (just as we have the `relationType` element elsewhere)? This would be great for some users at least, otherwise they may be compelled to encode, out of the textual element, a minimal description of the `agent`, `place,` `function` or `subject` referred to, in addition to using `referrinString`, which would be somewhat redundant. 
I hope I am clear.

**Comment by kerstarno** [comment]
> Hi everybody, what about adding to the new `referringString` element an attribute to specify the kind of relation that exists between the records described and the entity that is referred to (just as we have the `relationType` element elsewhere)? This would be great for some users at least, otherwise they may be compelled to encode, out of the textual element, a minimal description of the `agent`, `place,` `function` or `subject` referred to, in addition to using `referrinString`, which would be somewhat redundant. I hope I am clear.

I've added this suggestion as #111 for the next milestone.
