### ISSUE TITLE
Create a separate section for elements established as entities

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#68]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: In reviewing EAD, the conceptual approaches to its elements and its relation to Records in Contexts, the EAD sub-team has concluded that there are three types of entities, currently encoded as part of descriptive information, which should rather be emphasised as related entities of certain importance. That importance results from EAD's relation with its sibling standard EAC-CPF (referring to the element `<agent>` (#58)), with the standard for functions (currently under development by TS-EAS and referring to the element`<function>` (#61)), and with standards such as Records in Contexts or PREMIS, but also standards from related cultural heritage domains that include the concept of instantiations, representations, manifestations, or expressions of the "thing" being described (new element `<formAvailable>` (#65)). to represent this entity of instantiations is to be established, combining the three current elements. 
* To emphasise these three elements and the related entities they represent, the EAD sub-team has decided during their meeting on 15 December 2023, that these elements should be moved from their current place within the EAD structure and that there should be a dedicated section for them in the definition of `<archDesc>` and numbered and unnumbered `<c>` elements. 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level and - if applicable - the intermediate levels (printed in italics).**_ 

- [x] **Adapt the definition of `<archDesc>` and numbered and unnumbered `<c>` elements to the following structure**
  - [x] Have `<identificationData>` as required and not repeatable sub-element (as it already is in EAD3)
  - [x] _Add the plural elements `<agents>`, `<formsAvailable>`, and `<functions> ` as optional and not repeatable_
    - [ ] The concept of plural elements is new in EAD, but adopting the approach already known from EAC-CPF
    - [x] `<agents>` requires at least one `<agent>` sub-element and allows for an optional `<descriptiveNote>` as sub-element
    - [x] `<formsAvailable>` requires at least one `<formAvailable>` sub-element and allows for an optional `<descriptiveNote>` as sub-element
    - [x] `<functions>` requires at least one `<function>` sub-element and allows for an optional `<descriptiveNote>` as sub-element (`<functions>` hereby becomes a shared element between EAD and EAC-CPF
    - [x] All three plural elements allow for the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@localType`, `@localTypeDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@conventionDeclarationReference`, and the option to include attributes form any other namespace
  - [x] _Have the following elements allowing for longer descriptive texts as optional and repeatable_
    - [x] `<otherFindAid>`, `<publicationNote>` (renamed from `<bibliography>`, #66), `<relatedMaterial>`, `<separatedMaterial>`, `<accessConditions>` (renamed from `<accessrestrict>`, #60), `<useConditions>` (renamed from `<userestrict>`, #60), `<accruals>`, `<sourceOfAcquisition>` (renamed from `<acqInfo>`, #66), `<appraisal>`, `<arrangement>`, `<biogHist>`, `<custodHist>`, `<filePlan>`, `<otherDescriptiveInfo>` (renamed from `<odd>`, #66), `<physicalOrTechnicalRequirements>` (renamed from `<physTech>`, #66), `<preferCite>`, `<processInfo>`, `<scopeContent>`, and `<subjectHeadings>` (replacing `<controlAccess>` and `<index>`, #67); (**note:** for `<legalStatus>` see #5) 
  - [x] Have `<descriptionOfComponents>` as optional, **not** repeatable sub-element for `<archDesc>` and `<c>` respectively `<c02>`, `<c03>`, etc. as optional and repeatable sub-elements for unnumbered and numbered <c> elements 
    - [x] Remove `<thead>` as optional sub-elements of numbered and unnumbered `<c>` elements

**Comment by fordmadox** [comment]
Just a note that I'd like to discuss the name "formsAvailable", as I think that there might be a better choice for that one.

**Comment by fordmadox** [comment]
I took a shot at adding this.  Just let me know what still needs to be changed.

**Comment by fordmadox** [comment]
Ahh.. .the reason I added the localType pair to functions was to align with EAC.  I did the same for the rest of the new plural elements, like `agents` (though not listed above).  Let me know if any of those attributes should be removed.  If so, then we'll also need EAC-related tickets eventually.
