### ISSUE TITLE
Replace `<emph>` with `<span>` for alignment with EAC-CPF

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#71]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: In the context of aligning the EAS and in the context of other changes about formatting and mixed content (see #35, #47, and #70), `<emph>` is replaced by `<span>`. 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the intermediate level (printed in italic) or the lowest level of the list as applicable.**_ 

- [x] **Replace `<emph>` with `<span>`**
  - [x] `<span>` uses `@style` as an optional attribute with data type normalizedString, where `<emph>` used `@render` with a fixed list of values
  - [x] _`<span>`_
    - [x] May contain text 
    - [x] Includes the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@localType`, `@localTypeDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, and `@conventionDeclarationReference`
    - [x] Allows for the inclusion of attributes from any other namespace

**Comment by kerstarno** [comment]
@fordmadox - I added this one, as we didn't have it mentioned directly in any of the other issues so far, even though the change was confirmed and assumed. 

While both schemas, the XSD and the RNG, do not include `<emph>` anymore and use `<span>` instead, the optional attributes `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`, which are available for `<span>` in EAC-CPF are currently missing and would need to be added.

**Comment by fordmadox** [comment]
Updated, so ready for testing again.

**Comment by kerstarno** [comment]
Re-tested with the XSD and the RNG and can confirm that this is now implemented as expected.
